// 11-theme registry. Palettes verified from each theme's official
// spec. Studio (gallery-safe neutral/teal) + the 10 most popular software themes.
// Default on first launch = Dracula (vivid warm purple/pink).

import { DEFAULT_ANIM, DEFAULT_GLASS, DEFAULT_SPRING } from "./tokens";
import type { ColorRoles, GlassTokens, ThemePreset } from "./types";

export const DEFAULT_THEME_ID = "dracula";

// Themes share DEFAULT_GLASS; a preset may pass a small glass override (e.g. the
// glossier default) without affecting the other ten.
function preset(
  id: string,
  name: string,
  hue: string,
  colors: ColorRoles,
  glassOverride?: Partial<GlassTokens>,
): ThemePreset {
  return {
    id,
    name,
    hue,
    colors,
    glass: glassOverride ? { ...DEFAULT_GLASS, ...glassOverride } : DEFAULT_GLASS,
    spring: DEFAULT_SPRING,
    animations: DEFAULT_ANIM,
  };
}

export const PRESETS: ThemePreset[] = [
  preset("studio", "Studio", "neutral / teal (gallery-safe)", {
    bg: "#0e0f13",
    surface: "#16181d",
    elevated: "#1d2027",
    border: "#ffffff14",
    textPrimary: "#e6e8ec",
    textSecondary: "#8b919c",
    primary: "#2dd4bf",
    secondary: "#14b8a6",
    success: "#34d399",
    warning: "#f59e0b",
    error: "#f43f5e",
    info: "#38bdf8",
  }),
  preset("tokyo-night", "Tokyo Night", "cool navy / neon", {
    bg: "#1a1b26",
    surface: "#16161e",
    elevated: "#292e42",
    border: "#3b4261",
    textPrimary: "#c0caf5",
    textSecondary: "#565f89",
    primary: "#7aa2f7",
    secondary: "#bb9af7",
    success: "#9ece6a",
    warning: "#e0af68",
    error: "#f7768e",
    info: "#7dcfff",
  }),
  preset(
    "dracula",
    "Dracula",
    "warm vibrant",
    {
      bg: "#282a36",
      surface: "#343746",
      elevated: "#44475a",
      border: "#44475a",
      textPrimary: "#f8f8f2",
      textSecondary: "#6272a4",
      primary: "#bd93f9",
      secondary: "#ff79c6",
      success: "#50fa7b",
      warning: "#f1fa8c",
      error: "#ff5555",
      info: "#8be9fd",
    },
    // Glossier glass for the default theme (others keep DEFAULT_GLASS).
    { cardOpacity: 0.58, cardBlur: 20, borderRadius: 14 },
  ),
  preset("nord", "Nord", "cool arctic muted", {
    bg: "#2e3440",
    surface: "#3b4252",
    elevated: "#434c5e",
    border: "#4c566a",
    textPrimary: "#d8dee9",
    textSecondary: "#4c566a",
    primary: "#88c0d0",
    secondary: "#81a1c1",
    success: "#a3be8c",
    warning: "#ebcb8b",
    error: "#bf616a",
    info: "#8fbcbb",
  }),
  preset("catppuccin-mocha", "Catppuccin Mocha", "cool pastel", {
    bg: "#1e1e2e",
    surface: "#313244",
    elevated: "#45475a",
    border: "#6c7086",
    textPrimary: "#cdd6f4",
    textSecondary: "#a6adc8",
    primary: "#cba6f7",
    secondary: "#89b4fa",
    success: "#a6e3a1",
    warning: "#f9e2af",
    error: "#f38ba8",
    info: "#89dceb",
  }),
  preset("gruvbox", "Gruvbox", "warm retro earth", {
    bg: "#282828",
    surface: "#3c3836",
    elevated: "#504945",
    border: "#665c54",
    textPrimary: "#ebdbb2",
    textSecondary: "#928374",
    primary: "#fe8019",
    secondary: "#8ec07c",
    success: "#b8bb26",
    warning: "#fabd2f",
    error: "#fb4934",
    info: "#83a598",
  }),
  preset("one-dark-pro", "One Dark Pro", "cool balanced", {
    bg: "#282c34",
    surface: "#21252b",
    elevated: "#2c313c",
    border: "#3b4048",
    textPrimary: "#abb2bf",
    textSecondary: "#7f848e",
    primary: "#61afef",
    secondary: "#c678dd",
    success: "#98c379",
    warning: "#e5c07b",
    error: "#e06c75",
    info: "#56b6c2",
  }),
  preset("solarized-dark", "Solarized Dark", "precise low-contrast", {
    bg: "#002b36",
    surface: "#073642",
    elevated: "#073642",
    border: "#586e75",
    textPrimary: "#839496",
    textSecondary: "#586e75",
    primary: "#268bd2",
    secondary: "#2aa198",
    success: "#859900",
    warning: "#b58900",
    error: "#dc322f",
    info: "#268bd2",
  }),
  preset("monokai", "Monokai", "warm candy accents", {
    bg: "#272822",
    surface: "#2d2e27",
    elevated: "#3e3d32",
    border: "#49483e",
    textPrimary: "#f8f8f2",
    textSecondary: "#75715e",
    primary: "#f92672",
    secondary: "#66d9ef",
    success: "#a6e22e",
    warning: "#e6db74",
    error: "#fb4934",
    info: "#66d9ef",
  }),
  preset("night-owl", "Night Owl", "deep teal / navy", {
    bg: "#011627",
    surface: "#0b2942",
    elevated: "#1d3b53",
    border: "#122d42",
    textPrimary: "#d6deeb",
    textSecondary: "#637777",
    primary: "#82aaff",
    secondary: "#c792ea",
    success: "#22da6e",
    warning: "#ffeb95",
    error: "#ef5350",
    info: "#7fdbca",
  }),
  preset("rose-pine", "Rosé Pine", "cozy mauve pastel", {
    bg: "#191724",
    surface: "#1f1d2e",
    elevated: "#26233a",
    border: "#403d52",
    textPrimary: "#e0def4",
    textSecondary: "#908caa",
    primary: "#c4a7e7",
    secondary: "#ebbcba",
    success: "#9ccfd8",
    warning: "#f6c177",
    error: "#eb6f92",
    info: "#31748f",
  }),
];

export const PRESET_MAP: Record<string, ThemePreset> = Object.fromEntries(
  PRESETS.map((p) => [p.id, p]),
);

export function getPreset(id: string | null | undefined): ThemePreset {
  return (id && PRESET_MAP[id]) || PRESET_MAP[DEFAULT_THEME_ID];
}
